### ISSUE TITLE
Add alt text to img tags

### ISSUE THREAD

**Issue by bovem** [bovem/old.bovem.github.io#15]
Add the text specified below in `alt` attribute of `<img>` tags in respective HTML files.
- In `_layout/article.html` line 95. Text: "Article Header Image"
- In `/index.html` 
   - line 55. Text: "DataWiz Project Logo "
   - line 66. Text: "OpenCourser Project Logo"
   - line 77. Text: "Stock Tracker Logo "
   - line 88. Text: "Linear Algrebra Logo "
   - line 88. Text: "Bovem Logo "
- In `/credits.html`
   - line 50. Text: "Photo by Tim Johnson on Unsplash"
   - line 61. Text: "Photo by Jeswin Thomas on Unsplash"

**Comment by Ronqn** [comment]
Hello, I'll do it, will submit PR when it's done.
