### ISSUE TITLE
Changing about.html to homepage and index.html to blog.html

### ISSUE THREAD

**Issue by bovem** [bovem/old.bovem.github.io#27]
https://bovem.netlify.app/index.html -> https://bovem.netlify.app/blog.html
https://bovem.netlify.app/about.html -> https://bovem.netlify.app/index.html

While opening https://bovem.netlify.app I should be redirected to "About" page

**Comment by bovem** [comment]
@silentwraith03 can you look into this?

**Comment by lowkeyypal** [comment]
sure will do

**Comment by bovem** [comment]
Resolved in #28 . Thanks @silentwraith03
